### ISSUE TITLE
Rule: MA0025, MA0025, S1135

### ISSUE THREAD

**Issue by davidkallesen** [atc-net/atc-coding-rules#11]
### Rule summary

|             | Value |
| ----------- |------------------------------------------------|
| Title       | MA0025 Implement the functionality instead of throwing NotImplementedException  |
| CheckId     | MA0025 |
| Category    | ? |
| Link        | https://github.com/meziantou/Meziantou.Analyzer/blob/master/docs/Rules/MA0025.md |

### What is the problem

This rule sounds very nice as a starting point.
But in practice, we offen need `// TODO:` and `NotImplementedExecption` when we scaffold method-body's, and will do the actual implementation later of just handover to a co-worker.

`S1135` is about TODO's

### Suggestion

disable this rule in root .editorconfig with dotnet_diagnostic.MS0025.severity = suggestion

**Comment by egil** [comment]
Only turn it on in `dotnet build -c release`?

**Comment by davidkallesen** [comment]
@egil Since we are working with the base rule `TreatWarningsAsErrors=true`, then a rule with warning will become an error and therefore not an option other than to turn it off with `severity=none` otherwise we should vote for `severity=error`.

**Comment by davidkallesen** [comment]
https://github.com/atc-net/atc-coding-rules/blob/main/documentation/CodeAnalyzersRules/Meziantou/MA0025.md

https://github.com/atc-net/atc-coding-rules/blob/main/documentation/CodeAnalyzersRules/Meziantou/MA0026.md

https://github.com/atc-net/atc-coding-rules/blob/main/documentation/CodeAnalyzersRules/SonarAnalyzerCSharp/S1135.md
