### ISSUE TITLE
Rule: MA0003 Add argument name to improve readability

### ISSUE THREAD

**Issue by davidkallesen** [atc-net/atc-coding-rules#13]
### Rule summary

|             | Value |
| ----------- |------------------------------------------------|
| Title       | MA0003 Add argument name to improve readability |
| CheckId     | MA0003 |
| Category    | Style |
| Link        | https://github.com/meziantou/Meziantou.Analyzer/blob/master/docs/Rules/MA0003.md |

### What is the problem

The first time I saw this rule I did not like it and would suggest it should be disables, but after reading up on the rule, I will now say it is very relevant with the arguments for readability.

Therefor: Just follow the rule - see 'How to fix violations'

### Suggestion

enable this rule in root .editorconfig with dotnet_diagnostic.MS0003.severity = error

**Comment by kimlundjohansen** [comment]
Treat as Info

**Comment by egil** [comment]
Suggest having it as `= info`

**Comment by MrAndersPedersen** [comment]
root/Suggestion

**Comment by davidkallesen** [comment]
https://github.com/atc-net/atc-coding-rules/blob/main/documentation/CodeAnalyzersRules/Meziantou/MA0003.md
