### ISSUE TITLE
Rule: SA1133 Do Not Combine Attributes

### ISSUE THREAD

**Issue by perkops** [atc-net/atc-coding-rules#16]
### Rule summary

|             | Value |
| ----------- |------------------------------------------------|
| Title       | SA1133DoNotCombineAttributes |
| CheckId     | SA1133 |
| Category    | Readability Rules |
| Link        | https://github.com/DotNetAnalyzers/StyleCopAnalyzers/blob/master/documentation/SA1133.md |

### What is the problem

Two or more attributes appeared within the same set of square brackets.

For test projects, its nice to have the two attribute next to each other- the two attributes "belong" to each other.

```[Theory, AutoNSubstituteData]```

### Suggestion

disable this rule in test / .editorconfig with dotnet_diagnostic.SA1133.severity = none

**Comment by MrAndersPedersen** [comment]
Root/suggestion
Test  NONE

**Comment by davidkallesen** [comment]
https://github.com/atc-net/atc-coding-rules/blob/main/documentation/CodeAnalyzersRules/StyleCop/SA1133.md
