### ISSUE TITLE
Rule: VSTHRD200 Use Async suffix for async methods

### ISSUE THREAD

**Issue by perkops** [atc-net/atc-coding-rules#17]
### Rule summary

|             | Value |
| ----------- |------------------------------------------------|
| Title       | VSTHRD200 Use Async suffix for async methods |
| CheckId     | VSTHRD200 |
| Category    | Naming Rules |
| Link        | https://github.com/Microsoft/vs-threading/blob/master/doc/analyzers/VSTHRD200.md |

### What is the problem

The .NET Guidelines for async methods includes that such methods should have names that include an "Async" suffix.

Methods that return awaitable types such as Task or ValueTask should have an Async suffix. Methods that do not return awaitable types should not use the Async suffix.

This should not be necessary for test projects - since a test methods name is describing the intended functionality and not async structure.

### Suggestion

disable this rule in test / .editorconfig with dotnet_diagnostic.VSTHRD200.severity = none

**Comment by egil** [comment]
In addition to that, I dont think it always makes sense in non libraries as well. So I vote to make this a suggestion rather than a warning in non-test projects.

**Comment by LarsSkovslund** [comment]
I agree, this rule should be disabled for tests projects, but put a great value in having it in the codebase as it makes code-review easy and the caller is not in doubt that this is indeed an async method call.

Bottom-line having this rule on, enhances readability for developers on any levels.

**Comment by cjakobsen** [comment]
Definitely don't disable for non-test projects, I will even vote for not disabling it at all as I like to have the same rules everywhere.

**Comment by perkops** [comment]
Actually dont Think this is relevant anymore since we removed this analyzer.

**Comment by MrAndersPedersen** [comment]
not relevant anymore since we removed this analyzer.
