### ISSUE TITLE
Rule: SA1623 Property Summary Documentation Must Match Accessors

### ISSUE THREAD

**Issue by perkops** [atc-net/atc-coding-rules#18]
### Rule summary

|             | Value |
| ----------- |------------------------------------------------|
| Title       | SA1623PropertySummaryDocumentationMustMatchAccessors |
| CheckId     | SA1623 |
| Category    | Documentation Rules |
| Link        | https://github.com/DotNetAnalyzers/StyleCopAnalyzers/blob/master/documentation/SA1623.md |

### What is the problem

The documentation text within a C# property's <summary> tag does not match the accessors within the property.

### Suggestion

disable this rule in root .editorconfig with dotnet_diagnostic.SA1623.severity = none

**Comment by egil** [comment]
Lets make this a suggestion.

**Comment by kimlundjohansen** [comment]
Added SA1611, SA1625 to this as they are very similar.

**Comment by davidkallesen** [comment]
@kimlundjohansen Please create a issue with the issue template for each rule - and make a link in the issue with that #issue-number-link like #18. Otherwise it is hard to use in the rule-suppress-process documentation.

**Comment by davidkallesen** [comment]
@perkops Please provide a code example with the problem and some arguments for disabling it.

**Comment by MrAndersPedersen** [comment]
will be disabled  in root .editorconfig

**Comment by davidkallesen** [comment]
https://github.com/atc-net/atc-coding-rules/blob/main/documentation/CodeAnalyzersRules/StyleCop/SA1623.md
