### ISSUE TITLE
Rule: MA0028 Optimize StringBuilder usage

### ISSUE THREAD

**Issue by davidkallesen** [atc-net/atc-coding-rules#19]
### Rule summary

|             | Value |
| ----------- |------------------------------------------------|
| Title       | MA0028 Optimize StringBuilder usage |
| CheckId     | MA0028 |
| Category    | Performance |
| Link        | https://github.com/meziantou/Meziantou.Analyzer/blob/master/docs/Rules/MA0028.md |

### What is the problem

I don't like this rule... because the use of string interpolation often provides better readability, and the performance problem here is in the compiler - and the compiler needs to be corrected instead.
Until the compiler is fixed, it is not a issue in real world scenarios.

### Suggestion

disable this rule in root .editorconfig with `dotnet_diagnostic.MA0028.severity = none`

**Comment by cjakobsen** [comment]
Some of the cases looks to be relevant, change to info level.

**Comment by davidkallesen** [comment]
https://github.com/atc-net/atc-coding-rules/blob/main/documentation/CodeAnalyzersRules/Meziantou/MA0028.md
