### ISSUE TITLE
How we name our tests

### ISSUE THREAD

**Issue by egil** [atc-net/atc-coding-rules#20]
The name of our tests is one of the most important parts of writing tests, thus, I think it would be good to have a general convention for how we write the names of our tests.

My own preference is to be as wordy as needed, but no more _than_ needed, and follow the _given - when - then_ pattern, mostly without using those words, e.g. for a test of a simple add method on a calculator: `add called with a and b results in a plus b` (this would perhaps be a theory).

**Comment by perkops** [comment]
What does this have todo with the coding-rules? Maybe belongs in another repo?

**Comment by egil** [comment]
I think it is as relevant to discuss as all the other style rules we are covering in this repo. Just because it doesn't have an analyzer that can detect if we are doing it right, we can still use this repo to document how we like to write our test names. And test names are super important to get consistent, as they make it much easier to understand- and reason about a test.

**Comment by davidkallesen** [comment]
@egil The "How we name our tests" belongs to another forum, unless you can point out a rule in one of the `.editorconfig` files that potentially have a issue, and then please use the issue template if possible.

Otherwise I will close this issue after x-mas.

**Comment by egil** [comment]
> @egil The "How we name our tests" belongs to another forum, unless you can point out a rule in one of the `.editorconfig` files that potentially have a issue, and then please use the issue template if possible.
> 
> Otherwise I will close this issue after x-mas.

Let's discuss this in the next code jam meeting. As I've already stated, i think topics like this fits perfectly in here.
