### ISSUE TITLE
Rule: SA1204 Static Elements Must Appear Before Instance Elements

### ISSUE THREAD

**Issue by kimlundjohansen** [atc-net/atc-coding-rules#22]
### Rule summary

|             | Value |
| ----------- |------------------------------------------------|
| Title       | SA1204StaticElementsMustAppearBeforeInstanceElements |
| CheckId     | SA1204 |
| Category    | Ordering Rules |
| Link        | https://github.com/DotNetAnalyzers/StyleCopAnalyzers/blob/master/documentation/SA1204.md |

### What is the problem

I do not see ordering of static / non-static methods as an issue and some freedom should be allowed.

### Suggestion

disable this rule in root .editorconfig with dotnet_diagnostic.SA1204.severity = none

**Comment by LarsSkovslund** [comment]
I agree, have been "forced" to rearrange my private/static method by this rule.
As it brings no apparent value to readability or otherwise I agree, we should disable this rule.

**Comment by egil** [comment]
The only reason I would want to keep this around would be if we can control the order of types such that it is the one that we implicitly follow. 
But even if can do that, this might be too nitpicky and NOT offer the necessary freedom to structure the code so it works best in the given situation. If we can control the order, I am probably leaning towards having this as a `suggestion`.

**Comment by egil** [comment]
Also, there is a related rule, `SA1202`, which is similarly annoying.

**Comment by MrAndersPedersen** [comment]
disable this rule in root .editorconfig with dotnet_diagnostic.SA1204.severity = none

**Comment by davidkallesen** [comment]
https://github.com/atc-net/atc-coding-rules/blob/main/documentation/CodeAnalyzersRules/StyleCop/SA1204.md
