### ISSUE TITLE
Rule: SA1201 Elements Must Appear In The Correct Order

### ISSUE THREAD

**Issue by kimlundjohansen** [atc-net/atc-coding-rules#23]
### Rule summary

|             | Value |
| ----------- |------------------------------------------------|
| Title       | SA1201ElementsMustAppearInTheCorrectOrder |
| CheckId     | SA1201 |
| Category    | Ordering Rules |
| Link        | https://github.com/DotNetAnalyzers/StyleCopAnalyzers/blob/master/documentation/SA1201.md |

### What is the problem
The rule goes against a common practice advocated by Microsoft in samples etc. for as long as I can remember.

### Suggestion

disable this rule in root .editorconfig with dotnet_diagnostic.SA1201.severity = none

**Comment by elnigno** [comment]
I find it strange to place Properties after the constructor, in my experience is to place them before. Personally I would disable this rule.

**Comment by egil** [comment]
It looks as if we can control the order with a stylecop.json file. It might be worth it to keep this rule around, if we can actually get the order normally use: https://github.com/DotNetAnalyzers/StyleCopAnalyzers/blob/master/documentation/Configuration.md

That said, this is a rule that is very dogmatic, so I tend to be in favor of `none`.

**Comment by MrAndersPedersen** [comment]
David makes an update.

The rule goes against a common practice -> disable this rule in root

**Comment by MrAndersPedersen** [comment]
disable this rule in root .editorconfig with dotnet_diagnostic.SA1201.severity = none

**Comment by davidkallesen** [comment]
https://github.com/atc-net/atc-coding-rules/blob/main/documentation/CodeAnalyzersRules/StyleCop/SA1201.md
