### ISSUE TITLE
Rule: MA0006 Use String.Equals instead of equality operator

### ISSUE THREAD

**Issue by kimlundjohansen** [atc-net/atc-coding-rules#24]
### Rule summary

|             | Value |
| ----------- |------------------------------------------------|
| Title       | Use String.Equals instead of equality operator |
| CheckId     | MA0006 |
| Category    | ? |
| Link        | https://github.com/meziantou/Meziantou.Analyzer/blob/master/docs/Rules/MA0006.md |

### What is the problem

This does not improve readability as the rules description claims.

### Suggestion

disable this rule in root .editorconfig with dotnet_diagnostic.MA0006.severity = none

**Comment by egil** [comment]
What `StringComparison` style is used with `a == b`? If it is not `StringComparison.Ordinal`, then `a.Equals(b, StringComparison.Ordinal` will perform better.

Besides that, I agree that it does NOT improve readability.

**Comment by cjakobsen** [comment]
This [documentation](https://docs.microsoft.com/en-us/dotnet/csharp/how-to/compare-strings) from Microsoft also speaks against using == for comparison so I think we should keep it.

**Comment by MrAndersPedersen** [comment]
Please red comment from cjacobsen.

**Comment by rickykaare** [comment]
As far as I understand using `==` for comparing two strings will be the same as using `string.Equals()` with `StringComparison.Ordinal` (given that the two strings are of type string, and not cast to e.g. object).

In my mind, this way of comparing string are by far the most commonly used, so applying the MA0006 rule in general would add a lot of clutter.

In most cases I think it would be very obvious if you need to compare using case-insensitivity or the CurrentCulture, and then use the `string.Equals()` instead.

**Comment by egil** [comment]
> As far as I understand using `==` for comparing two strings will be the same as using `string.Equals()` with `StringComparison.Ordinal`

That's surprising to me @rickykaare, but you are right, at least if we read the latest [string.cs code](https://source.dot.net/#System.Private.CoreLib/String.Comparison.cs,23). Here we see that `EqualsHelper` is called when from both the operators `==`/`!=` and from the `Equals` method when `StringComparison.Ordinal` is set.

That takes the performance concern out of the equation for me. The question that is left is whether we want to be explicit in our code about our intentions, e.g. signaling that, yes, we have thought about culture and this is what we want.

**Comment by egil** [comment]
ROOT=NONE, because in most cases we are only doing ordinal comparisons anyway, and == leads to cleaner code.

Exception to this rule when working on an application that is multi cultured.

**Comment by davidkallesen** [comment]
https://github.com/atc-net/atc-coding-rules/blob/main/documentation/CodeAnalyzersRules/Meziantou/MA0006.md
