### ISSUE TITLE
Rule: SA1623

### ISSUE THREAD

**Issue by kimlundjohansen** [atc-net/atc-coding-rules#25]
### Rule summary

|             | Value |
| ----------- |------------------------------------------------|
| Title       | SA1623PropertySummaryDocumentationMustMatchAccessors |
| CheckId     | [SA1623 |
| Category    | [Example: Maintainability Rules] |
| Link        | [Example: https://github.com/DotNetAnalyzers/StyleCopAnalyzers/blob/master/documentation/SA1413.md] |

### What is the problem

Rule should dictate how we document code.

### Suggestion

disable this rule in root .editorconfig with dotnet_diagnostic.SA1623.severity = none

**Comment by perkops** [comment]
Already open in issue #18
