### ISSUE TITLE
Rule: MA0048 File name must match type name

### ISSUE THREAD

**Issue by kimlundjohansen** [atc-net/atc-coding-rules#26]
### Rule summary

|             | Value |
| ----------- |------------------------------------------------|
| Title       | File name must match type name |
| CheckId     | MA0048 |
| Category    | ? |
| Link        | https://github.com/meziantou/Meziantou.Analyzer/blob/master/docs/Rules/MA0048.md |

### What is the problem

We name files after a different pattern. Example: CommandFixture<TParameters, TResult> = CommandFixture{TParameters,TResult}.cs

### Suggestion

disable this rule in root .editorconfig with dotnet_diagnostic.MA0048.severity = none

**Comment by egil** [comment]
Lets get the patterns we name after documented. I have seen we use the `CommandFixture<TParameters, TResult> => CommandFixture{TParameters,TResult}.cs` pattern in some cases, but not all. Also, do we have other file naming schemes besides this?

Either way, I think this should either be `none` or` info`

**Comment by LarsSkovslund** [comment]
It should be `none`. Consider a scenario where multiple generic classes with the same name you would have to guess what class is behind file `classname'1.cs`, `classname'2.cs` and `classname'3.cs`.

> I have disabled this rule for `EventStore` as I'm using the above naming @egil mentioned.

**Comment by davidkallesen** [comment]
Have created a issue @ meziantou: https://github.com/meziantou/Meziantou.Analyzer/issues/213

**Comment by LarsSkovslund** [comment]
After the latest release `MA0048` now supports `CommandFixture{T1,T2}.cs` so my vote would be to keep it.

**Comment by egil** [comment]
Decision: ROOT = ERROR
Analyzer did not support the feature, but it does now in the latest version.

**Comment by davidkallesen** [comment]
https://github.com/atc-net/atc-coding-rules/blob/main/documentation/CodeAnalyzersRules/Meziantou/MA0048.md
