### ISSUE TITLE
Rule: SA1629 Documentation Text Must End With A Period

### ISSUE THREAD

**Issue by egil** [atc-net/atc-coding-rules#28]
### Rule summary

|             | Value |
| ----------- |------------------------------------------------|
| Title       | SA1629DocumentationTextMustEndWithAPeriod |
| CheckId     | SA1629 |
| Category    | Documentation Rules |
| Link        | https://github.com/DotNetAnalyzers/StyleCopAnalyzers/blob/master/documentation/SA1629.md |

### What is the problem

No. It must not always end with a period. Sometimes you end with a code snippet, or other text where a period doesnt make sense.

A better alternative is to install a plugin like https://marketplace.visualstudio.com/items?itemName=EWoodruff.VisualStudioSpellCheckerVS2017andLater that helps with spelling in code and VS.

### Suggestion

`none`

**Comment by egil** [comment]
**Decision is:** ROOT=NONE
Nitpicky. People can install a spellchecker in VS if they need help with this...

**Comment by davidkallesen** [comment]
https://github.com/atc-net/atc-coding-rules/blob/main/documentation/CodeAnalyzersRules/StyleCop/SA1629.md
