### ISSUE TITLE
Test rule: IDE0058 Expression value is never used

### ISSUE THREAD

**Issue by egil** [atc-net/atc-coding-rules#29]
### Rule summary

|             | Value |
| ----------- |------------------------------------------------|
| Title       | Remove unnecessary expression value (IDE0058) |
| CheckId     | IDE0058  |
| Category    | Style |
| Link        | https://docs.microsoft.com/en-us/dotnet/fundamentals/code-analysis/style-rules/ide0058 |

### What is the problem

When writing tests and using e.g. NSubsitute to verify that a call has happened, you often have to fake calling it to create the assertion. If the method we are asserting was called/not called returns a value, this rule will complain that we have a returned value that needs to be assigned to either a variable or a discard (`_`).

### Suggestion

```
[tests/**.cs]
dotnet_diagnostic.IDE0058.severity = silent         # IDE0058: Expression value is never used
```

**Comment by cjakobsen** [comment]
I find this to be a good rule, you can see that the author has thought about the return value and not just forgotten about it. I vote for keeping it.

**Comment by egil** [comment]
> I find this to be a good rule, you can see that the author has thought about the return value and not just forgotten about it. I vote for keeping it.

Do you also see the value of that in tests? I don't want to disable this in production code, just test code.

**Comment by egil** [comment]
To show an example, where think this rule doesnt add value, consider this:

```c#
[Theory, AutoNSubstituteData]
public async Task MasterAssigned_Doesnt_Change_Master_When_Recipe_Does_Not_Exists(
    [Frozen] IRecipeRepository repository,
    RecipeBuilder sut,
    MasterAssigned @event,
    CancellationToken cancellationToken)
{
    repository.GetByIdAsync(default, default).ReturnsForAnyArgs(default(Recipe));

    await sut.ExecuteEventAsync(@event, cancellationToken);

    _ = repository.DidNotReceive().StoreAsync(Arg.Any<Recipe>(), Arg.Is(cancellationToken));
    _ = repository.DidNotReceive().StoreAsync(Arg.Any<Recipe[]>(), Arg.Is(cancellationToken));
}
```

vs this:

```c#
[Theory, AutoNSubstituteData]
public async Task MasterAssigned_Doesnt_Change_Master_When_Recipe_Does_Not_Exists(
    [Frozen] IRecipeRepository repository,
    RecipeBuilder sut,
    MasterAssigned @event,
    CancellationToken cancellationToken)
{
    repository.GetByIdAsync(default, default).ReturnsForAnyArgs(default(Recipe));

    await sut.ExecuteEventAsync(@event, cancellationToken);

    repository.DidNotReceive().StoreAsync(Arg.Any<Recipe>(), Arg.Is(cancellationToken));
    repository.DidNotReceive().StoreAsync(Arg.Any<Recipe[]>(), Arg.Is(cancellationToken));
}
```

To me, this is very much the same consideration as with `string.Equals` vs `==`. Sure, with `_ =` I make it explicit that I do not care about the value. But to be honest, that should be obvious in this context.

**Comment by egil** [comment]
Decision: ROOT = ERROR

**Comment by davidkallesen** [comment]
https://github.com/atc-net/atc-coding-rules/blob/main/documentation/CodeAnalyzersRules/MicrosoftCodeAnalysis/IDE0058.md

**Comment by perkops** [comment]
Are we still sure on this?

E.g. in a console app:

```csharp
services.AddLogging(logging =>
{
     logging.AddConsole().SetMinimumLevel(LogLevel.Information);
     logging.AddDebug().SetMinimumLevel(LogLevel.Trace);
});
```

Becomes
```csharp
_ = services.AddLogging(logging =>
{
     _ = logging.AddConsole().SetMinimumLevel(LogLevel.Information);
     _ = logging.AddDebug().SetMinimumLevel(LogLevel.Trace);
});
```

**Comment by JKrag** [comment]
Another example that will get a lot uglier with this rule:

```csharp
    requestHeaders.Add("Accept");
    requestHeaders.Add("Accept-Encoding");
    requestHeaders.Add("Cache-Control");
    requestHeaders.Add("Pragma");
    requestHeaders.Add("Upgrade-Insecure-Requests");
    requestHeaders.Add("User-Agent");
    requestHeaders.Add("X-Forwarded-Host");
    requestHeaders.Add("X-Forwarded-Proto");
```

They all just return a true/false depending on whether the element was already in the hash set. 

Does changing all of these to:
```csharp
 _ = requestHeaders.Add("X-Forwarded-Proto");
``` 
really provide value that counters the additional verbosity? maybe it does, I am not sure. I just wanted to add the examples to the mix for consideration.

The same goes for e.g. services:

```csharp
    services.AddSingleton<Utilities>();
    services.AddScoped<IUpdater, UpdaterService>();
    services.AddScoped<IFileUtility, FileUtility>();
    services.AddScoped<IUriHelper, UriHelper>();
```

**Comment by egil** [comment]
This rules is starting to annoy more and more in production code as well, e.g. here is an example of a fluent interface/api where it complains when we do not continue the fluent chain...:

![image](https://user-images.githubusercontent.com/105649/109135888-755bbc00-774f-11eb-87e1-df03d82c34a1.png)

Has to be this to make things compile:

![image](https://user-images.githubusercontent.com/105649/109136058-9fad7980-774f-11eb-81ff-d5f1793daaad.png)

**Comment by egil** [comment]
Decision: ROOT = NONE.

Refer to arguments above, where e.g. build pattern based code suffer, we have reversed to NONE.

**Comment by davidkallesen** [comment]
Commit: https://github.com/atc-net/atc-coding-rules/commit/522c1b9fe721dc1625cefd55da9e655008144de8
