### ISSUE TITLE
Test rule: CS4014 Because this call is not awaited, execution of the current method continues before the call is completed

### ISSUE THREAD

**Issue by egil** [atc-net/atc-coding-rules#30]
### Rule summary

|             | Value |
| ----------- |------------------------------------------------|
| Title       | Because this call is not awaited, execution of the current method continues before the call is completed |
| CheckId     | CS4014  |
| Category    | Compiler |
| Link        | https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/compiler-messages/cs4014 |

### What is the problem

When writing tests and using e.g. NSubsitute to verify that a call has happened, you often have to fake calling it to create the assertion. If the method we are asserting was called/not called is an Async method, this rule will complain that the call was not awaited. 

### Suggestion

```
[tests/**.cs]
dotnet_diagnostic.CS4014.severity = suggestion      # CS4014: Because this call is not awaited, execution of the current method continues before the call is completed
```

**Comment by LarsSkovslund** [comment]
We always use `_ = mock.Received(1).MethodAsync(...)` when asserting to avoid this.

**Comment by egil** [comment]
@LarsSkovslund exactly, with this rules severity adjusted, you can just write `mock.Received(1).MethodAsync(...)`, which I think removes unneeded noise from tests.

**Comment by egil** [comment]
Decision: ROOT = ERROR

**Comment by davidkallesen** [comment]
https://github.com/atc-net/atc-coding-rules/blob/main/documentation/CodeAnalyzersRules/MicrosoftCompilerErrors/CS4014.md
