### ISSUE TITLE
Rule: SA1625 Element Documentation  Must Not Be Copied And Pasted

### ISSUE THREAD

**Issue by kimlundjohansen** [atc-net/atc-coding-rules#31]
### Rule summary

|             | Value |
| ----------- |------------------------------------------------|
| Title       | SA1625ElementDocumentationMustNotBeCopiedAndPasted |
| CheckId     | SA1625 |
| Category    | Documentation Rules |
| Link        | https://github.com/DotNetAnalyzers/StyleCopAnalyzers/blob/master/documentation/SA1625.md |

### What is the problem

Forcing always to have parameter documentation added is a waste of time.

### Suggestion

Set it to none or info.

**Comment by egil** [comment]
This is a "it depends" rule for me. In general, it is super useful to users of libraries/nugets that all public stuff has code documentation. It adds a lot of value, especially to new users of the library.

However, for internal projects/libraries, that is only used within a solution, code documentation is often a waste of time.

**Comment by cjakobsen** [comment]
I looks like this rule is not about having the parameter documentation always but about not having the same text. If this really happens often that the same text is used it makes sense to change to info, otherwise I vote for keeping it.

**Comment by perkops** [comment]
Closing since this issue is not about having documentation, but having duplicate documentation.
