### ISSUE TITLE
Rule: SA1649 File Name Must Match Type Name

### ISSUE THREAD

**Issue by kimlundjohansen** [atc-net/atc-coding-rules#32]
### Rule summary

|             | Value |
| ----------- |------------------------------------------------|
| Title       | SA1649FileNameMustMatchTypeName |
| CheckId     | SA1649 |
| Category    | Documentation Rules |
| Link        | https://github.com/DotNetAnalyzers/StyleCopAnalyzers/blob/master/documentation/SA1649.md |

### What is the problem

We name EndpointFixture<TRequest, TResource> as EndpointFixture{TRequest,TResponse} - the rule dowsn't allow it.

### Suggestion

disable this rule in root .editorconfig with dotnet_diagnostic.SA1649.severity = none

**Comment by cjakobsen** [comment]
Investigate why this does not work. According to the documentation it should be allowed if file naming styles are setup correct (see here https://github.com/DotNetAnalyzers/StyleCopAnalyzers/blob/master/documentation/Configuration.md#file-naming-conventions)

**Comment by egil** [comment]
This rule also overlaps with of the Meziantou.Analyzer (#26), so this or that should be completely disabled.

**Comment by davidkallesen** [comment]
@egil or @cjakobsen can you verify this SA1649 has exact behaviour as [MA0048](https://github.com/atc-net/atc-coding-rules/blob/main/documentation/CodeAnalyzersRules/Meziantou/MA0048.md)

Then I will suggest `root/.editorconfig` with `severity = error`

**Comment by cjakobsen** [comment]
@davidkallesen From what I can tell after testing it they are the same. There are more information in SA1649 so I suggest we keep that and suppress MA0048.

**Comment by egil** [comment]
This replaces the decision from #26 .

**Comment by davidkallesen** [comment]
Commit: https://github.com/atc-net/atc-coding-rules/commit/522c1b9fe721dc1625cefd55da9e655008144de8
