### ISSUE TITLE
Rule: CA1014 - Mark assemblies with CLSCompliant

### ISSUE THREAD

**Issue by cjakobsen** [atc-net/atc-coding-rules#35]
### Rule summary

|             | Value |
| ----------- |------------------------------------------------|
| Title       | CA1014: Mark assemblies with CLSCompliantAttribute |
| CheckId     | CA1014 |
| Category    | Microsoft.Design |
| Link        | https://docs.microsoft.com/en-us/dotnet/fundamentals/code-analysis/quality-rules/ca1014 |

### What is the problem
Test assemblies that are generated by ATC generator can cause this. 

### Suggestion
How to handle this for test code, is this something that makes sense to suppress?

**Comment by egil** [comment]
I tried this with bUnit, but found it way to restrictive to be useful. I dont see that in many other open source libs, and think it might be a leftover from the .net framework area.

**Comment by egil** [comment]
I suggest setting this to 

**ROOT = NONE**

**Comment by egil** [comment]
Decision; ROOT = NONE (remember to add to `<NoWarn>` in build props.

Too many libraries and c# language features we are using daily is not compatible with this.

**Comment by davidkallesen** [comment]
Commit: https://github.com/atc-net/atc-coding-rules/commit/522c1b9fe721dc1625cefd55da9e655008144de8
