### ISSUE TITLE
Update Meziantou.Analyzer version >= 1.0.645

### ISSUE THREAD

**Issue by davidkallesen** [atc-net/atc-coding-rules#37]
We want to update Meziantou.Analyzer to v. 1.0.645.

In order to do this, we need all downstream Github/AzureDevOps pipelines to implement dotnet restore steps differently, otherwise these pipelines will fail.

**Comment by perkops** [comment]
Example fix on Azure DevOps:

![image](https://user-images.githubusercontent.com/43060445/105332102-86eff800-5bd4-11eb-93d1-a9f2389d8c33.png)

**Comment by perkops** [comment]
For GitHub actions/workflows:

Ensure to utilize .NET 5.0.x

![image](https://user-images.githubusercontent.com/43060445/105332282-b999f080-5bd4-11eb-8cd8-2f0e7a93b891.png)

**Comment by egil** [comment]
Isnt this issue resolved?

**Comment by perkops** [comment]
Not in all repositories/azure devops repositories. So if we bump this, we need all "customers" of this, to change build steps accordingly.

**Comment by egil** [comment]
If we bump it here, it wont affect other repositories, unless people go and upgrade or run the rules upgrade tool. Should this issue stick around until all projects have upgraded? It doesn't feel right to me.

**Comment by davidkallesen** [comment]
This is upgraded to `1.0.646` in https://github.com/atc-net/atc-coding-rules/commit/0a5c15cfd635b52de49a961d3d88e2878641fe6c
