### ISSUE TITLE
NSubstitute.Analyzers.CSharp

### ISSUE THREAD

**Issue by perkops** [atc-net/atc-coding-rules#38]
Do we want this Analyzer added?

https://www.nuget.org/packages/NSubstitute.Analyzers.CSharp/

If so - we need to add the following to our `distribution/build/code-analysis.props` file.

`<PackageReference Include="NSubstitute.Analyzers.CSharp" Version="1.0.14" />`

**Comment by egil** [comment]
Are we sure this is not automatically included when we reference NSubstitute, just like xUnit includes its own analyzers when it is referenced automatically?

**Comment by perkops** [comment]
Lars already added it as you can see. We just need that referenced PR approved asap.

**Comment by LarsSkovslund** [comment]
I have just tested and the analyzer is **not** included with the `NSubstitute` package.
