### ISSUE TITLE
CA1812: Avoid uninstantiated internal classes

### ISSUE THREAD

**Issue by egil** [atc-net/atc-coding-rules#48]
### Rule summary

|             | Value |
| ----------- |------------------------------------------------|
| Title       | CA1812: Avoid uninstantiated internal classes |
| CheckId     | CA1812 |
| Category    | Performance |
| Link        | https://docs.microsoft.com/en-us/dotnet/fundamentals/code-analysis/quality-rules/ca1812 |

### What is the problem

This rule flags classes that are not instantiated in a library and are internal as not being used. In the [docs for the rule](https://docs.microsoft.com/en-us/dotnet/fundamentals/code-analysis/quality-rules/ca1812), it says it is safe to suppress the rule if the classes is instantiated through other means, e.g. an IOC container.

One example is when we have an public interface (`IMyEndpoint`) and an internal implementation (`MyEndpoint`) that is registered in an `IServiceCollection` through an extension method. In this case, the rule still gives a warning, even though the class is actually used. 

### Suggestion

ROOT: NONE.

**Comment by MrAndersPedersen** [comment]
Decision: ROOT: NONE.
