### ISSUE TITLE
Test rule: CA1068: CancellationToken parameters must come last

### ISSUE THREAD

**Issue by egil** [atc-net/atc-coding-rules#50]
### Rule summary

|             | Value |
| ----------- |------------------------------------------------|
| Title       | CA1068: CancellationToken parameters must come last |
| CheckId     | CA1068 |
| Category    | Design |
| Link        | https://docs.microsoft.com/en-us/dotnet/fundamentals/code-analysis/quality-rules/ca1068|

### What is the problem

When writing tests/theories that receive their input through arguments generated by e.g. AutoFixture, it doesnt always make sense to have the CancellationToken as the last argument.

### Suggestion

**TEST = none**

**Comment by davidkallesen** [comment]
Can you give a code example. Otherwise, I think it is a good practice to also do it in test code. Can't see why inconsistent code style should suddenly be better.

**Comment by egil** [comment]
So this rule is generally about public APIs, not test methods. The problem is that test methods also look like a public API, but really isn't. So the spirit of the rule generally isn't meant to include test methods, something I think is highlighted by the options to turn this rule of for specific types/methods.

For the test pattern we are using now with AutoData generating the SUT and input data, I like to have test input as the first arguments and then the SUT as the last argument. That sort of matches how test would be written without the use of AutoData, where input data is declared before the SUT, especially in the cases where the SUT actually takes the data as input.

**Comment by egil** [comment]
DECISION: TEST = NONE

**Comment by davidkallesen** [comment]
Commit: https://github.com/atc-net/atc-coding-rules/commit/522c1b9fe721dc1625cefd55da9e655008144de8
