### ISSUE TITLE
Rule: CA1002 replaces MA0016

### ISSUE THREAD

**Issue by egil** [atc-net/atc-coding-rules#51]
The two rules are the same. This I think we should prefer the one from Microsoft and simply disable MA0016, and replace the doc/decision file (#12) for it with one for [CA1002](https://docs.microsoft.com/en-us/dotnet/fundamentals/code-analysis/quality-rules/ca1002).

**Comment by davidkallesen** [comment]
Sounds like a good idea, then the PR #49 is irellevant.

**Comment by davidkallesen** [comment]
https://github.com/atc-net/atc-coding-rules/blob/main/documentation/CodeAnalyzersRules/Meziantou/MA0016.md
