### ISSUE TITLE
SA1202 (ElementsMustBeOrderedByAccess) should be covered by decision for SA1201

### ISSUE THREAD

**Issue by egil** [atc-net/atc-coding-rules#52]
[SA1202](https://github.com/DotNetAnalyzers/StyleCopAnalyzers/blob/master/documentation/SA1202.md) should be covered by decision for SA1201 (https://github.com/atc-net/atc-coding-rules/issues/23).

**Comment by davidkallesen** [comment]
Please use the Rule-issue template.

**Comment by davidkallesen** [comment]
Commit: https://github.com/atc-net/atc-coding-rules/commit/522c1b9fe721dc1625cefd55da9e655008144de8
