### ISSUE TITLE
Rule: CA1305 replaces MA0011 

### ISSUE THREAD

**Issue by cjakobsen** [atc-net/atc-coding-rules#57]
### Rule summary

|             | Value |
| ----------- |------------------------------------------------|
| Title       | IFormatProvider is missing |
| CheckId     | MA0011 |
| Category    | Globaliaztion |
| Link        | https://docs.microsoft.com/en-us/dotnet/fundamentals/code-analysis/quality-rules/ca1305 |

### What is the problem

Duplicate warnings are generated for the same issue.

### Suggestion

Disable MA0011 and prefer the Microsoft rule.

**Comment by jhoejgaard** [comment]
Decision
https://github.com/meziantou/Meziantou.Analyzer/blob/main/docs/comparison-with-other-analyzers.md
Disable MA0011
