### ISSUE TITLE
Rule: MA0038 Make method static - Same as CA1822

### ISSUE THREAD

**Issue by davidkallesen** [atc-net/atc-coding-rules#58]
### Rule summary

|             | Value |
| ----------- |------------------------------------------------|
| Title       | Make method static |
| CheckId     | MA0038 |
| Category    | Design |
| Link        | https://github.com/meziantou/Meziantou.Analyzer/blob/main/docs/Rules/MA0038.md |

### What is the problem

MA0038 is a duplicate of MS CA1822

And CA1822 should be set as `info` since it is a `Performance` 

### Suggestion

enable this rule in root .editorconfig with `dotnet_diagnostic.CA1822.severity = info`
disable this rule in root .editorconfig with `dotnet_diagnostic.MA0038.severity = none`

**Comment by jhoejgaard** [comment]
Decision
enable this rule in root .editorconfig with dotnet_diagnostic.CA1822.severity = warning
disable this rule in root .editorconfig with dotnet_diagnostic.MA0038.severity = none
